# Generated by Django 5.2.4 on 2025-07-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('produto', models.CharField(max_length=255)),
                ('numero_serie', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('andamento', 'Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='andamento', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('data_crianca', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
