# Generated by Django 5.2.4 on 2025-07-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='data_crianca',
            new_name='data_criacao',
        ),
    ]
